[package]
name = "helix-tui"
version = "0.6.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
description = """
A library to build rich terminal user interfaces or dashboards
"""
edition = "2021"
license = "MPL-2.0"
categories = ["editor"]
repository = "https://github.com/helix-editor/helix"
homepage = "https://helix-editor.com"
include = ["src/**/*", "README.md"]

[features]
default = ["crossterm", "termini"]

[dependencies]
bitflags = "2.4"
cassowary = "0.3"
unicode-segmentation = "1.10"
crossterm = { version = "0.27", optional = true }
termini = { version = "1.0", optional = true }
serde = { version = "1", "optional" = true, features = ["derive"] }
once_cell = "1.18"
log = "~0.4"
helix-core = { version = "0.6", path = "../helix-core" }
tokio = { version = "1", features = [
    "rt",
    # "rt-multi-thread",
    "io-util",
    # "io-std",
    "time",
    # "process",
    "macros",
    # "fs",
    "parking_lot",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
helix-view = { version = "0.6", path = "../helix-view", default-features = false }

# TODO(wasm32) re-enable conditional when this is fixed: https://github.com/rust-lang/cargo/issues/12821
# so `cargo build` 'just works' and `cargo build --no-default-features --target wasm32-unknown-unknown` as well
# [target.'cfg(not(target_family = "wasm"))'.dependencies]
# helix-view = { version = "0.6", path = "../helix-view", default-features = true }
